site_name: Favo & Maya's Referrals

theme:
  name: material
  features:
    - announce.dismiss
  custom_dir: overrides
  logo: assets/avatar.png
  favicon: assets/avatar.png
  palette:
    - scheme: default
      primary: blue-grey
      accent: amber

nav:
  - Home: index.md
  - Personal Bank Accounts: personal-bank.md
  - Business Bank Accounts: business-bank.md
  - Brokerage: brokerage.md
  - Crypto: crypto.md
  - Personal Credit Cards: personal-credit-cards.md
  - Business Credit Cards: business-credit-cards.md
  - Shopping Portals: shopping-portals.md
  - Money Tools: money-tools.md

markdown_extensions:
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css




